version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  fastapi:
    build:
      context: ../backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_PORT=4566
    volumes:
      - ../backend/app:/app  # Mount the FastAPI app directory to the container
  test:
    build:
      context: ../backend/app
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app  # Mount the backend directory to the container
    command: ["pytest", "--disable-warnings"]
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_PORT=4566
networks:
  my_network:
    driver: bridge