"""Ensure uniqueness of data

Revision ID: 59f7d8b7808a
Revises: b70be3d2bf8e
Create Date: 2024-11-26 10:55:17.259499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59f7d8b7808a'
down_revision: Union[str, None] = 'b70be3d2bf8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_metadata', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.drop_index('ix_image_metadata_filename', table_name='image_metadata')
    op.create_unique_constraint('_image_metadata_uc', 'image_metadata', ['file_name', 'date', 'patient_id', 'source_id', 'diagnosis'])
    op.create_index(op.f('ix_image_metadata_file_name'), 'image_metadata', ['file_name'], unique=False)
    op.drop_column('image_metadata', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_metadata', sa.Column('filename', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_image_metadata_file_name'), table_name='image_metadata')
    op.drop_constraint('_image_metadata_uc', 'image_metadata', type_='unique')
    op.create_index('ix_image_metadata_filename', 'image_metadata', ['filename'], unique=False)
    op.drop_column('image_metadata', 'file_name')
    # ### end Alembic commands ###
